### Get request to fetch data from an API
GET https://jsonplaceholder.typicode.com/posts/1
Accept: application/json

### Post request to send data to an API
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
    "title": "foo",
    "body": "bar",
    "userId": 1
}
